name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # install node & deps
      - name: Install node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: "14.X"
      - name: Install deps
        run: npm install

      # push actions
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs/.vitepress/dist
